version: "3.8"
services:
  web:
    container_name: content_project
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000 
    environment:
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=
      - DB_HOST=pg
      - DB_PORT=5432
      - DATABASE=postgres
    depends_on:
      - pg
  pg:
    container_name: pg_content_management
    image: postgres:13.2-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: content_management_db
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5440:5432
    volumes:
      - ./data:/var/lib/postgresql/data 

  pgadmin:
    container_name: pgadmin_content_management_container
    image: dpage/pgadmin4:5.2
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_LISTEN_PORT: 5433
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    ports:
      - 5433:5433 
    depends_on:
      - pg
